In [11]:
from src.runner import preprocess
preprocess()

Processing Center for Advanced Life Cycle Engineering cells: 100%|██████████| 7/7 [00:01<00:00,  4.08it/s]

0 processed, 7 skipped

Processing Hawaii Natural Energy Institute cells: 100%|██████████| 15/15 [00:03<00:00,  3.78it/s]

0 processed, 15 skipped

Processing Oxford cells: 100%|██████████| 8/8 [00:01<00:00,  5.27it/s]

8 processed, 0 skipped

Processing Oak Ridge National Lab cells: 100%|██████████| 253/253 [01:19<00:00,  3.19it/s]

230 processed, 23 skipped

Processing Sandia National Lab cells: 100%|██████████| 30/30 [00:06<00:00,  4.63it/s]
Processing Sandia National Lab cells: 100%|██████████| 24/24 [00:02<00:00, 11.70it/s]
Processing Sandia National Lab cells: 100%|██████████| 32/32 [00:04<00:00,  7.56it/s]

74 processed, 12 skipped

Processing Underwriters Lab - Purdue University cells: 100%|██████████| 22/22 [00:02<00:00,  7.86it/s]

21 processed, 1 skipped

In [37]:
from src.data import BatteryData
oxford_data = BatteryData.load('data/preprocessed/OX_1-1_pouch_LCO_40C_0-100_2-1.84C_a_timeseries.pkl')
# oxford_data.print_description()
ts = next(t for t in oxford_data.timeseries_data)
ts.display()

           time_in_s  temperature_in_C
0       0.000000e+00            40.026
1       9.990000e-01            40.051
2       1.999000e+00            39.988
3       2.999000e+00            39.976
4       3.999000e+00            39.964
...              ...               ...
460376  5.518128e+07            40.737
460377  5.518128e+07            40.750
460378  5.518128e+07            40.688
460379  5.518128e+07            40.725
460380  5.518128e+07            40.750

[460381 rows x 2 columns]

In [36]:
from src.data import BatteryData
filename = 'data/preprocessed/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
cell = BatteryData.load(filename)
# cell.print_description()

ts = next(t for t in cell.timeseries_data)
ts.display()

Timeseries Data description: tc1, positive-terminal

         time_in_s  temperature_in_C
0         0.000000         22.364101
1         0.099609         22.358707
2         0.199219         22.365358
3         0.298828         22.381090
4         0.398438         22.315783
...            ...               ...
38712  3856.078125         29.106949
38713  3856.177734         29.090010
38714  3856.277344         29.108253
38715  3856.376953         29.104151
38716  3856.465820         29.110058

[38717 rows x 2 columns]

In [2]:
from src.data.train_test_split import *
from src.utils.config import YamlHandler
from sklearn.model_selection import train_test_split

configs=YamlHandler('configs/dummy.yaml').read_yaml()

x1, x2, y1, y2 = load_train_test_split(configs=configs)
print(len(x1), len(x2), len(y1), len(y2))

584 146 584 146

In [6]:
from src.utils.config import YamlHandler
from src.data.battery_data import BatteryData

handler = YamlHandler('configs/dummy.yaml')
config = handler.read_yaml()


config = config.get('train_test_split', config)
config

def testconfig(configs, data=None):
    configs = configs.get('train_test_split', configs) # open configs if needed

    for filter in configs.battery_filters:
        print(filter, type(filter))

        filterattr = getattr(configs.battery_filters, filter)
        dataattr = getattr(data, filter, None)
        print(filterattr)
        print(dataattr)

        print(dataattr in filterattr)
        print()

    print(any(getattr(data, filter, None) in getattr(configs.battery_filters, filter) for filter in configs.battery_filters))


filename = 'data/preprocessed/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
cell = BatteryData.load(filename)

testconfig(config, cell)
cell.anode_material

anode_material <class 'str'>
['graphitee']
graphite
False

cathode_material <class 'str'>
['NMC']
LFP
False

False

'graphite'

In [8]:
from src.utils.config import import_config
from pathlib import Path

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
# config = config['train_test_split']
x1, x2, y1, y2 = load_train_test_split(configs=config)
# print(len(x1), len(x2), len(y1), len(y2))
x2

Missing expected config fields: ['t']

[       time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 13655        NaN               NaN
 13656        NaN               NaN
 13657        NaN               NaN
 13658        NaN               NaN
 13659        NaN               NaN

 [13660 rows x 2 columns],
       time_in_s  temperature_in_C
 0          1.06              16.0
 1          2.06              16.0
 2          3.06              16.0
 3          4.06              16.0
 4          5.06              16.0
 ...         ...               ...
 3969    3970.06              30.3
 3970    3971.06              30.3
 3971    3972.06              30.4
 3972    3973.06              30.4
 3973    3974.06              30.4

 [3974 rows x 2 columns],
       time_in_s  temperature_in_C
 0         0.000          23.03782
 1         0.266          22.99610
 2         0.499          23.05346
 3         0.767          23.01175
 4         1.000          22.99089
 ...         ...               ...
 3374        NaN               NaN
 3375        NaN               NaN
 3376        NaN               NaN
 3377        NaN               NaN
 3378        NaN               NaN

 [3379 rows x 2 columns],
       time_in_s  temperature_in_C
 0          1.06              21.5
 1          2.06              21.5
 2          3.06              21.5
 3          4.06              21.5
 4          5.06              21.5
 ...         ...               ...
 4033    4034.06              42.9
 4034    4035.06              42.8
 4035    4036.06              42.8
 4036    4037.06              42.8
 4037    4038.06              42.9

 [4038 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000               NaN
 1          0.045               NaN
 2          0.119               NaN
 3          0.167               NaN
 4          0.212               NaN
 ...          ...               ...
 30799        NaN               NaN
 30800        NaN               NaN
 30801        NaN               NaN
 30802        NaN               NaN
 30803        NaN               NaN

 [30804 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000               NaN
 1          0.092               NaN
 2          0.137               NaN
 3          0.182               NaN
 4          0.234               NaN
 ...          ...               ...
 21099        NaN               NaN
 21100        NaN               NaN
 21101        NaN               NaN
 21102        NaN               NaN
 21103        NaN               NaN

 [21104 rows x 2 columns],
       time_in_s  temperature_in_C
 0          1.06              26.3
 1          2.06              26.3
 2          3.06              26.3
 3          4.06              26.3
 4          5.06              26.3
 ...         ...               ...
 2844    2845.06              31.0
 2845    2846.06              31.0
 2846    2847.06              31.0
 2847    2848.06              31.0
 2848    2849.06              31.0

 [2849 rows x 2 columns],
       time_in_s  temperature_in_C
 0         0.000               NaN
 1         0.099               NaN
 2         0.199               NaN
 3         0.299               NaN
 4         0.432               NaN
 ...         ...               ...
 3409        NaN               NaN
 3410        NaN               NaN
 3411        NaN               NaN
 3412        NaN               NaN
 3413        NaN               NaN

 [3414 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 13553        NaN               NaN
 13554        NaN               NaN
 13555        NaN               NaN
 13556        NaN               NaN
 13557        NaN               NaN

 [13558 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0            23.969
 1            0.2            23.989
 2            0.4            23.984
 3            0.6            24.002
 4            0.8            23.991
 ...          ...               ...
 12179        NaN               NaN
 12180        NaN               NaN
 12181        NaN               NaN
 12182        NaN               NaN
 12183        NaN               NaN

 [12184 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 12179        NaN               NaN
 12180        NaN               NaN
 12181        NaN               NaN
 12182        NaN               NaN
 12183        NaN               NaN

 [12184 rows x 2 columns],
       time_in_s  temperature_in_C
 0           0.0          16.95418
 1           0.1          16.98428
 2           0.2          16.98761
 3           0.3          16.97007
 4           0.5          16.98675
 ...         ...               ...
 7934        NaN               NaN
 7935        NaN               NaN
 7936        NaN               NaN
 7937        NaN               NaN
 7938        NaN               NaN

 [7939 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000               NaN
 1          0.085               NaN
 2          0.131               NaN
 3          0.176               NaN
 4          0.221               NaN
 ...          ...               ...
 30351        NaN               NaN
 30352        NaN               NaN
 30353        NaN               NaN
 30354        NaN               NaN
 30355        NaN               NaN

 [30356 rows x 2 columns],
          time_in_s  temperature_in_C
 0         0.000000         16.658043
 1         0.099609         16.666178
 2         0.199219         16.676691
 3         0.298828         16.662245
 4         0.398438         16.657530
 ...            ...               ...
 38674  3852.292969         25.458963
 38675  3852.392578         25.487658
 38676  3852.492188         25.475824
 38677  3852.591797         25.482180
 38678  3852.751953         25.505243

 [38679 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 20748        NaN               NaN
 20749        NaN               NaN
 20750        NaN               NaN
 20751        NaN               NaN
 20752        NaN               NaN

 [20753 rows x 2 columns],
          time_in_s  temperature_in_C
 0         0.000000         22.020054
 1         0.099609         22.017246
 2         0.199219         22.044052
 3         0.298828         22.024542
 4         0.398438         22.050463
 ...            ...               ...
 38802  3865.042969         35.759491
 38803  3865.142578         35.754448
 38804  3865.242188         35.726357
 38805  3865.341797         35.733757
 38806  3865.466797         35.688156

 [38807 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 18473        NaN               NaN
 18474        NaN               NaN
 18475        NaN               NaN
 18476        NaN               NaN
 18477        NaN               NaN

 [18478 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000               NaN
 1          0.099               NaN
 2          0.200               NaN
 3          0.299               NaN
 4          0.432               NaN
 ...          ...               ...
 11581        NaN               NaN
 11582        NaN               NaN
 11583        NaN               NaN
 11584        NaN               NaN
 11585        NaN               NaN

 [11586 rows x 2 columns],
       time_in_s  temperature_in_C
 0           0.0          17.36983
 1           0.2          17.34916
 2           0.3          17.34833
 3           0.4          17.35988
 4           0.5          17.36236
 ...         ...               ...
 6873        NaN               NaN
 6874        NaN               NaN
 6875        NaN               NaN
 6876        NaN               NaN
 6877        NaN               NaN

 [6878 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000               NaN
 1          0.076               NaN
 2          0.121               NaN
 3          0.188               NaN
 4          0.233               NaN
 ...          ...               ...
 21656        NaN               NaN
 21657        NaN               NaN
 21658        NaN               NaN
 21659        NaN               NaN
 21660        NaN               NaN

 [21661 rows x 2 columns],
       time_in_s  temperature_in_C
 0          1.06              20.2
 1          2.06              20.2
 2          3.06              20.2
 3          4.06              20.2
 4          5.06              20.2
 ...         ...               ...
 3810    3811.06              24.0
 3811    3812.06              24.1
 3812    3813.06              24.2
 3813    3814.06              24.3
 3814    3815.06              24.2

 [3815 rows x 2 columns],
          time_in_s  temperature_in_C
 0         0.000000         17.099846
 1         0.099609         17.094254
 2         0.199219         17.092842
 3         0.298828         17.095612
 4         0.398438         17.061268
 ...            ...               ...
 38674  3852.292969         25.716835
 38675  3852.392578         25.710743
 38676  3852.492188         25.702522
 38677  3852.591797         25.667789
 38678  3852.751953         25.693768

 [38679 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 15809        NaN               NaN
 15810        NaN               NaN
 15811        NaN               NaN
 15812        NaN               NaN
 15813        NaN               NaN

 [15814 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 21354        NaN               NaN
 21355        NaN               NaN
 21356        NaN               NaN
 21357        NaN               NaN
 21358        NaN               NaN

 [21359 rows x 2 columns],
       time_in_s  temperature_in_C
 0          1.06              23.6
 1          2.06              23.6
 2          3.06              23.6
 3          4.06              23.6
 4          5.06              23.6
 ...         ...               ...
 3864    3865.06              26.3
 3865    3866.06              26.3
 3866    3867.06              26.3
 3867    3868.06              26.3
 3868    3869.06              26.3

 [3869 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000               NaN
 1          0.047               NaN
 2          0.092               NaN
 3          0.148               NaN
 4          0.243               NaN
 ...          ...               ...
 27993        NaN               NaN
 27994        NaN               NaN
 27995        NaN               NaN
 27996        NaN               NaN
 27997        NaN               NaN

 [27998 rows x 2 columns],
       time_in_s  temperature_in_C
 0         0.000               NaN
 1         0.099               NaN
 2         0.199               NaN
 3         0.300               NaN
 4         0.433               NaN
 ...         ...               ...
 6122        NaN               NaN
 6123        NaN               NaN
 6124        NaN               NaN
 6125        NaN               NaN
 6126        NaN               NaN

 [6127 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0            23.780
 1            0.2            23.788
 2            0.4            23.791
 3            0.6            23.783
 4            0.8            23.795
 ...          ...               ...
 15163        NaN               NaN
 15164        NaN               NaN
 15165        NaN               NaN
 15166        NaN               NaN
 15167        NaN               NaN

 [15168 rows x 2 columns],
       time_in_s  temperature_in_C
 0           0.0               NaN
 1           0.1               NaN
 2           0.2               NaN
 3           0.3               NaN
 4           0.4               NaN
 ...         ...               ...
 9249        NaN               NaN
 9250        NaN               NaN
 9251        NaN               NaN
 9252        NaN               NaN
 9253        NaN               NaN

 [9254 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.5               NaN
 4            0.7               NaN
 ...          ...               ...
 10637        NaN               NaN
 10638        NaN               NaN
 10639        NaN               NaN
 10640        NaN               NaN
 10641        NaN               NaN

 [10642 rows x 2 columns],
          time_in_s  temperature_in_C
 0            0.059            22.857
 1           26.543            22.736
 2           36.362            22.766
 3           73.318            22.928
 4          149.617            23.299
 ...            ...               ...
 80360  7770781.782            32.199
 80361  7770901.791            32.263
 80362  7771021.800            32.293
 80363  7771141.810            32.533
 80364  7771261.820            32.392

 [80365 rows x 2 columns],
          time_in_s  temperature_in_C
 0            0.061            23.870
 1            6.179            23.870
 2            6.179            23.870
 3            6.226            23.840
 4          126.228            23.840
 ...            ...               ...
 70753  6805418.557            23.563
 70754  6805443.595            23.711
 70755  6805501.103            24.025
 70756  6805607.264            24.082
 70757  6805727.275            24.739

 [70758 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 13484        NaN               NaN
 13485        NaN               NaN
 13486        NaN               NaN
 13487        NaN               NaN
 13488        NaN               NaN

 [13489 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 24936        NaN               NaN
 24937        NaN               NaN
 24938        NaN               NaN
 24939        NaN               NaN
 24940        NaN               NaN

 [24941 rows x 2 columns],
       time_in_s  temperature_in_C
 0           0.0               NaN
 1           0.2               NaN
 2           0.3               NaN
 3           0.5               NaN
 4           0.7               NaN
 ...         ...               ...
 6790        NaN               NaN
 6791        NaN               NaN
 6792        NaN               NaN
 6793        NaN               NaN
 6794        NaN               NaN

 [6795 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000          23.16518
 1          0.099          23.14146
 2          0.200          23.16113
 3          0.299          23.16229
 4          0.399          23.17502
 ...          ...               ...
 15175        NaN               NaN
 15176        NaN               NaN
 15177        NaN               NaN
 15178        NaN               NaN
 15179        NaN               NaN

 [15180 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000          22.79251
 1          0.033          22.79251
 2          0.066          22.80760
 3          0.099          22.79425
 4          0.133          22.79425
 ...          ...               ...
 21722    766.341         105.47440
 21723    766.375         105.60000
 21724    766.409         105.54180
 21725    766.442         105.46400
 21726    766.477         105.56550

 [21727 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 21647        NaN               NaN
 21648        NaN               NaN
 21649        NaN               NaN
 21650        NaN               NaN
 21651        NaN               NaN

 [21652 rows x 2 columns],
        time_in_s  temperature_in_C
 0          0.000               NaN
 1          0.045               NaN
 2          0.090               NaN
 3          0.135               NaN
 4          0.180               NaN
 ...          ...               ...
 23027        NaN               NaN
 23028        NaN               NaN
 23029        NaN               NaN
 23030        NaN               NaN
 23031        NaN               NaN

 [23032 rows x 2 columns],
        time_in_s  temperature_in_C
 0           0.00               NaN
 1           0.05               NaN
 2           0.10               NaN
 3           0.15               NaN
 4           0.20               NaN
 ...          ...               ...
 20919        NaN               NaN
 20920        NaN               NaN
 20921        NaN               NaN
 20922        NaN               NaN
 20923        NaN               NaN

 [20924 rows x 2 columns],
       time_in_s  temperature_in_C
 0          1.06              21.1
 1          2.06              21.1
 2          3.06              21.1
 3          4.06              21.1
 4          5.06              21.1
 ...         ...               ...
 4033    4034.06              41.4
 4034    4035.06              41.5
 4035    4036.06              41.5
 4036    4037.06              41.5
 4037    4038.06              41.6

 [4038 rows x 2 columns],
       time_in_s  temperature_in_C
 0         0.000               NaN
 1         0.099               NaN
 2         0.200               NaN
 3         0.300               NaN
 4         0.400               NaN
 ...         ...               ...
 4408        NaN               NaN
 4409        NaN               NaN
 4410        NaN               NaN
 4411        NaN               NaN
 4412        NaN               NaN

 [4413 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 20616        NaN               NaN
 20617        NaN               NaN
 20618        NaN               NaN
 20619        NaN               NaN
 20620        NaN               NaN

 [20621 rows x 2 columns],
        time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...

In [12]:
y2

AttributeError: 'list' object has no attribute 'float'

In [5]:
from src.utils import import_config
from pathlib import Path
from src.data.train_test_split import load_train_test_split

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
# config = config['train_test_split']
x1, x2, y1, y2 = load_train_test_split(configs=config)
# print(len(x1), len(x2), len(y1), len(y2))
x2[0]

Missing expected config fields: ['t']

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 957.29it/s]

array([[1.06000e+00, 2.62000e+01],
       [2.06000e+00, 2.63000e+01],
       [3.06000e+00, 2.62000e+01],
       ...,
       [2.84706e+03, 3.22000e+01],
       [2.84806e+03, 3.22000e+01],
       [2.84906e+03, 3.21000e+01]])

In [8]:
from src.utils import import_config, YamlHandler
from src.data.train_test_split import *

configs = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
extract_attributes_from_dir(configs=configs['train_test_split'])

Missing expected config fields: ['t']

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3043.58it/s]

([array([[6.00000000e-02, 2.47720000e+01],
         [7.20400000e+00, 2.47720000e+01],
         [7.20400000e+00, 2.47720000e+01],
         ...,
         [1.23596109e+07, 3.02020000e+01],
         [1.23597309e+07, 3.04090000e+01],
         [1.23598509e+07, 3.03480000e+01]]),
  array([[1.00110000e+01, 2.61550000e+01],
         [2.00140000e+01, 2.61550000e+01],
         [3.00230000e+01, 2.62310000e+01],
         ...,
         [9.49708384e+06, 2.89790000e+01],
         [9.49708487e+06, 2.90400000e+01],
         [9.49708518e+06, 2.90400000e+01]]),
  array([[1.06000e+00, 2.13000e+01],
         [2.06000e+00, 2.13000e+01],
         [3.06000e+00, 2.13000e+01],
         ...,
         [4.02706e+03, 1.98000e+01],
         [4.02806e+03, 1.98000e+01],
         [4.02906e+03, 1.98000e+01]]),
  array([[1.06000e+00, 2.13000e+01],
         [2.06000e+00, 2.13000e+01],
         [3.06000e+00, 2.13000e+01],
         ...,
         [4.02706e+03, 2.15000e+01],
         [4.02806e+03, 2.15000e+01],
         [4.02906e+03, 2.14000e+01]]),
  array([[1.06000e+00, 2.14000e+01],
         [2.06000e+00, 2.14000e+01],
         [3.06000e+00, 2.15000e+01],
         ...,
         [4.02706e+03, 2.03000e+01],
         [4.02806e+03, 2.04000e+01],
         [4.02906e+03, 2.04000e+01]]),
  array([[1.06000e+00, 2.15000e+01],
         [2.06000e+00, 2.15000e+01],
         [3.06000e+00, 2.15000e+01],
         ...,
         [4.02706e+03, 2.16000e+01],
         [4.02806e+03, 2.16000e+01],
         [4.02906e+03, 2.16000e+01]]),
  array([[1.06000e+00, 2.15000e+01],
         [2.06000e+00, 2.15000e+01],
         [3.06000e+00, 2.15000e+01],
         ...,
         [4.02706e+03, 2.14000e+01],
         [4.02806e+03, 2.14000e+01],
         [4.02906e+03, 2.14000e+01]]),
  array([[1.06000e+00, 2.14000e+01],
         [2.06000e+00, 2.14000e+01],
         [3.06000e+00, 2.14000e+01],
         ...,
         [4.02706e+03, 2.14000e+01],
         [4.02806e+03, 2.14000e+01],
         [4.02906e+03, 2.14000e+01]]),
  array([[6.20000000e-02, 2.76230000e+01],
         [2.53170000e+01, 2.74410000e+01],
         [1.02745000e+02, 2.74100000e+01],
         ...,
         [1.00184116e+07, 2.91370000e+01],
         [1.00185316e+07, 2.91070000e+01],
         [1.00186516e+07, 2.91500000e+01]]),
  array([[ 0.      , 23.126653],
         [ 0.045   , 23.084269],
         [ 0.09    , 23.126653],
         ...,
         [      nan,       nan],
         [      nan,       nan],
         [      nan,       nan]]),
  array([[ 0.     , 21.92809],
         [ 0.099  , 21.94331],
         [ 0.233  , 21.92283],
         ...,
         [     nan,      nan],
         [     nan,      nan],
         [     nan,      nan]]),
  array([[ 0.      , 22.22586 ],
         [ 0.085   , 22.113007],
         [ 0.146   , 22.115407],
         ...,
         [      nan,       nan],
         [      nan,       nan],
         [      nan,       nan]]),
  array([[ 0.     , 20.26574],
         [ 0.2    , 20.31437],
         [ 0.3    , 20.29465],
         ...,
         [     nan,      nan],
         [     nan,      nan],
         [     nan,      nan]]),
  array([[1.06000e+00, 2.30000e+01],
         [2.06000e+00, 2.29000e+01],
         [3.06000e+00, 2.30000e+01],
         ...,
         [3.79706e+03, 2.50000e+01],
         [3.79806e+03, 2.50000e+01],
         [3.79906e+03, 2.49000e+01]]),
  array([[1.06000e+00, 2.29000e+01],
         [2.06000e+00, 2.29000e+01],
         [3.06000e+00, 2.29000e+01],
         ...,
         [3.79706e+03, 2.94000e+01],
         [3.79806e+03, 2.94000e+01],
         [3.79906e+03, 2.94000e+01]]),
  array([[1.06000e+00, 2.29000e+01],
         [2.06000e+00, 2.29000e+01],
         [3.06000e+00, 2.29000e+01],
         ...,
         [3.79706e+03, 2.71000e+01],
         [3.79806e+03, 2.71000e+01],
         [3.79906e+03, 2.71000e+01]]),
  array([[1.06000e+00, 2.30000e+01],
         [2.06000e+00, 2.29000e+01],
         [3.06000e+00, 2.30000e+01],
         ...,
         [3.79706e+03, 2.48000e+01],
         [3.79806e+03, 2.48000e+01],
         [3.79906e+03, 2.48000e+01]]),
  array([[1.06000e+00, 2.30000e+01],
         [2.06000e+00, 2.30000e+01],
         [3.06000e+00, 2.30000e+01],
         ...,
         [3.79706e+03, 2.41000e+01],
         [3.79806e+03, 2.41000e+01],
         [3.79906e+03, 2.41000e+01]]),
  array([[1.06000e+00, 2.29000e+01],
         [2.06000e+00, 2.29000e+01],
         [3.06000e+00, 2.29000e+01],
         ...,
         [3.79706e+03, 2.86000e+01],
         [3.79806e+03, 2.86000e+01],
         [3.79906e+03, 2.86000e+01]]),
  array([[0.00000000e+00, 2.18024616e+01],
         [9.96093750e-02, 2.18443832e+01],
         [1.99218750e-01, 2.18176003e+01],
         ...,
         [3.85777148e+03, 3.14891434e+01],
         [3.85787109e+03, 3.14769707e+01],
         [3.85805469e+03, 3.15044746e+01]]),
  array([[0.00000000e+00, 2.18895874e+01],
         [9.96093750e-02, 2.19144096e+01],
         [1.99218750e-01, 2.19090519e+01],
         ...,
         [3.85777148e+03, 3.08935814e+01],
         [3.85787109e+03, 3.09137764e+01],
         [3.85805469e+03, 3.09217510e+01]]),
  array([[0.00000000e+00, 2.16126957e+01],
         [9.96093750e-02, 2.15824184e+01],
         [1.99218750e-01, 2.15967369e+01],
         ...,
         [3.85777148e+03, 2.98545437e+01],
         [3.85787109e+03, 2.99003963e+01],
         [3.85805469e+03, 2.98445415e+01]]),
  array([[0.00000000e+00, 2.13267994e+01],
         [9.96093750e-02, 2.12862129e+01],
         [1.99218750e-01, 2.13227329e+01],
         ...,
         [3.85777148e+03, 3.04303436e+01],
         [3.85787109e+03, 3.04127769e+01],
         [3.85805469e+03, 3.04503479e+01]]),
  array([[0.00000000e+00, 2.14335480e+01],
         [9.96093750e-02, 2.14060230e+01],
         [1.99218750e-01, 2.14507446e+01],
         ...,
         [3.85777148e+03, 3.91167793e+01],
         [3.85787109e+03, 3.90884628e+01],
         [3.85805469e+03, 3.90728111e+01]]),
  array([[0.00000000e+00, 2.16161919e+01],
         [9.96093750e-02, 2.16254997e+01],
         [1.99218750e-01, 2.16024132e+01],
         ...,
         [3.85777148e+03, 3.72399368e+01],
         [3.85787109e+03, 3.72134857e+01],
         [3.85805469e+03, 3.72468414e+01]]),
  array([[ 0.     , 22.91085],
         [ 0.099  , 22.89694],
         [ 0.2    , 22.89926],
         ...,
         [     nan,      nan],
         [     nan,      nan],
         [     nan,      nan]]),
  array([[ 0.      , 22.30192 ],
         [ 0.092   , 22.224294],
         [ 0.137   , 22.464364],
         ...,
         [      nan,       nan],
         [      nan,       nan],
         [      nan,       nan]]),
  array([[ 0.   , 23.78 ],
         [ 0.2  , 23.788],
         [ 0.4  , 23.791],
         ...,
         [   nan,    nan],
         [   nan,    nan],
         [   nan,    nan]]),
  array([[0.00000000e+00, 1.71730404e+01],
         [9.96093750e-02, 1.71787510e+01],
         [1.99218750e-01, 1.72083778e+01],
         ...,
         [3.81254883e+03, 1.95950031e+01],
         [3.81264844e+03, 1.95925636e+01],
         [3.81276758e+03, 1.96362286e+01]]),
  array([[0.00000000e+00, 1.73419170e+01],
         [9.96093750e-02, 1.73279247e+01],
         [1.99218750e-01, 1.73220940e+01],
         ...,
         [3.81254883e+03, 1.87880573e+01],
         [3.81264844e+03, 1.87590199e+01],
         [3.81276758e+03, 1.87791367e+01]]),
  array([[0.00000000e+00, 1.70995655e+01],
         [9.96093750e-02, 1.71071529e+01],
         [1.99218750e-01, 1.71091080e+01],
         ...,
         [3.81254883e+03, 2.27292652e+01],
         [3.81264844e+03, 2.27134132e+01],
         [3.81276758e+03, 2.27077503e+01]]),
  array([[0.00000000e+00, 1.67806892e+01],
         [9.96093750e-02, 1.67759724e+01],
         [1.99218750e-01, 1.67657700e+01],
         ...,
         [3.81254883e+03, 1.90438919e+01],
         [3.81264844e+03, 1.90696735e+01],
         [3.81276758e+03, 1.90597439e+01]]),
  array([[0.00000000e+00, 1.69132404e+01],
         [9.96093750e-02, 1.69401951e+01],
         [1.99218750e-01, 1.69273262e+01],
         ...,
         [3.81254883e+03, 2.12635860e+01],
         [3.81264844e+03, 2.12234249e+01],
         [3.81276758e+03, 2.12299194e+01]]),
  array([[0.00000000e+00, 1.71353741e+01],
         [9.96093750e-02, 1.71195431e+01],
         [1.99218750e-01, 1.71325722e+01],
         ...,
         [3.81254883e+03, 2.06748562e+01],
         [3.81264844e+03, 2.07179108e+01],
         [3.81276758e+03, 2.07335205e+01]]),
  array([[ 0.   , 24.055],
         [ 0.2  , 24.069],
         [ 0.4  , 24.057],
         ...,
         [   nan,    nan],
         [   nan,    nan],
         [   nan,    nan]]),
  array([[ 0.   , 24.322],
         [ 0.2  , 24.321],
         [ 0.4  , 24.318],
         ...,
         [   nan,    nan],
         [   nan,    nan],
         [   nan,    nan]]),
  array([[0.00000000e+00, 2.23641014e+01],
         [9.96093750e-02, 2.23587074e+01],
         [1.99218750e-01, 2.23653584e+01],
         ...,
         [3.85627734e+03, 2.91082535e+01],
         [3.85637695e+03, 2.91041508e+01],
         [3.85646582e+03, 2.91100578e+01]]),
  array([[0.00000000e+00, 2.24411469e+01],
         [9.96093750e-02, 2.24180565e+01],
         [1.99218750e-01, 2.23771839e+01],
         ...,
         [3.85627734e+03, 2.87740612e+01],
         [3.85637695e+03, 2.87831230e+01],
         [3.85646582e+03, 2.88047619e+01]]),
  array([[0.00000000e+00, 2.21124954e+01],
         [9.96093750e-02, 2.21416779e+01],
         [1.99218750e-01, 2.21480694e+01],
         ...,
         [3.85627734e+03, 2.84608040e+01],
         [3.85637695e+03, 2.84134789e+01],
         [3.85646582e+03, 2.84679470e+01]]),
  array([[0.00000000e+00, 2.18750076e+01],
         [9.96093750e-02, 2.18422508e+01],
         [1.99218750e-01, 2.18714905e+01],
         ...,
         [3.85627734e+03, 2.83762817e+01],
         [3.85637695e+03, 2.83725643e+01],
         [3.85646582e+03, 2.83789024e+01]]),
  array([[0.00000000e+00, 2.19755306e+01],
         [9.96093750e-02, 2.20073719e+01],
         [1.99218750e-01, 2.19559307e+01],
         ...,
         [3.85627734e+03, 3.46583862e+01],
         [3.85637695e+03, 3.46261139e+01],
         [3.85646582e+03, 3.46564865e+01]]),
  array([[0.00000000e+00, 2.21906357e+01],
         [9.96093750e-02, 2.21954441e+01],
         [1.99218750e-01, 2.21661167e+01],
         ...,
         [3.85627734e+03, 3.46625671e+01],
         [3.85637695e+03, 3.46922607e+01],
         [3.85646582e+03, 3.47060890e+01]]),
  array([[1.00000000e+01, 3.49010000e+01],
         [2.00020000e+01, 3.49060000e+01],
         [3.00070000e+01, 3.48970000e+01],
         ...,
         [5.08673074e+06, 3.46730000e+01],
         [5.08673175e+06, 3.46730000e+01],
         [5.08673175e+06, 3.46730000e+01]]),
  array([[ 0.      , 23.08612 ],
         [ 0.046   , 22.923763],
         [ 0.092   , 23.006146],
         ...,
         [      nan,       nan],
         [      nan,       nan],
         [      nan,       nan]]),
  array([[ 0.   , 23.772],
         [ 0.2  , 23.769],
         [ 0.4  , 23.76 ],
         ...,
         [   nan,    nan],
         [   nan,    nan],
         [   nan,    nan]]),
  array([[1.06000e+00, 1.84000e+01],
         [2.06000e+00, 1.84000e+01],
         [3.06000e+00, 1.84000e+01],
         ...,
         [4.06906e+03, 2.07000e+01],
         [4.07006e+03, 2.07000e+01],
         [4.07106e+03, 2.07000e+01]]),
  array([[1.06000e+00, 1.84000e+01],
         [2.06000e+00, 1.84000e+01],
         [3.06000e+00, 1.84000e+01],
         ...,
         [4.06906e+03, 2.09000e+01],
         [4.07006e+03, 2.08000e+01],
         [4.07106e+03, 2.08000e+01]]),
  array([[1.06000e+00, 1.85000e+01],
         [2.06000e+00, 1.85000e+01],
         [3.06000e+00, 1.85000e+01],
         ...,
         [4.06906e+03, 2.11000e+01],
         [4.07006e+03, 2.11000e+01],
         [4.07106e+03, 2.11000e+01]]),
  array([[1.06000e+00, 1.85000e+01],
         [2.06000e+00, 1.85000e+01],
         [3.06000e+00, 1.85000e+01],
         ...,
         [4.06906e+03, 2.07000e+01],
         [4.07006e+03, 2.07000e+01],
         [4.07106e+03, 2.08000e+01]]),
  array([[1.06000e+00, 1.84000e+01],
         [2.06000e+00, 1.84000e+01],
         [3.06000e+00, 1.84000e+01],
         ...,
         [4.06906e+03, 2.12000e+01],
         [4.07006e+03, 2.12000e+01],
         [4.07106e+03, 2.12000e+01]]),
  array([[1.06000e+00, 2.63000e+01],
         [2.06000e+00, 2.63000e+01],
         [3.06000e+00, 2.63000e+01],
         ...,
         [2.84706e+03, 3.10000e+01],
         [2.84806e+03, 3.10000e+01],
         [2.84906e+03, 3.10000e+01]]),
  array([[1.06000e+00, 2.62000e+01],
         [2.06000e+00, 2.62000e+01],
         [3.06000e+00, 2.62000e+01],
         ...,
         [2.84706e+03, 3.56000e+01],
         [2.84806e+03, 3.56000e+01],
         [2.84906e+03, 3.56000e+01]]),
  array([[1.06000e+00, 2.62000e+01],
         [2.06000e+00, 2.62000e+01],
         [3.06000e+00, 2.62000e+01],
         ...,
         [2.84706e+03, 2.87000e+01],
         [2.84806e+03, 2.88000e+01],
         [2.84906e+03, 2.88000e+01]]),
  array([[1.06000e+00, 2.63000e+01],
         [2.06000e+00, 2.63000e+01],
         [3.06000e+00, 2.63000e+01],
         ...,
         [2.84706e+03, 3.23000e+01],
         [2.84806e+03, 3.23000e+01],
         [2.84906e+03, 3.22000e+01]]),
  array([[1.06000e+00, 2.64000e+01],
         [2.06000e+00, 2.63000e+01],
         [3.06000e+00, 2.64000e+01],
         ...,
         [2.84706e+03, 3.07000e+01],
         [2.84806e+03, 3.07000e+01],
         [2.84906e+03, 3.07000e+01]]),
  array([[1.06000e+00, 2.62000e+01],
         [2.06000e+00, 2.63000e+01],
         [3.06000e+00, 2.62000e+01],
         ...,
         [2.84706e+03, 3.22000e+01],
         [2.84806e+03, 3.22000e+01],
         [2.84906e+03, 3.21000e+01]]),
  array([[ 0.      , 21.814499],
         [ 0.085   , 21.696056],
         [ 0.131   , 21.73609 ],
         ...,
         [      nan,       nan],
         [      nan,       nan],
         [      nan,       nan]]),
  array([[ 0.     , 22.25823],
         [ 0.099  , 22.24189],
         [ 0.199  , 22.23664],
         ...,
         [     nan,      nan],
         [     nan,      nan],
         [     nan,      nan]]),
  array([[0.00000000e+00, 2.21642818e+01],
         [9.96093750e-02, 2.21470051e+01],
         [1.99218750e-01, 2.21364136e+01],
         ...,
         [3.86524219e+03, 3.76952820e+01],
         [3.86534180e+03, 3.76879425e+01],
         [3.86546680e+03, 3.76739845e+01]]),
  array([[0.00000000e+00, 2.22037411e+01],
         [9.96093750e-02, 2.22123775e+01],
         [1.99218750e-01, 2.22036667e+01],
         ...,
         [3.86524219e+03, 3.68034630e+01],
         [3.86534180e+03, 3.67614326e+01],
         [3.86546680e+03, 3.67281876e+01]]),
  array([[0.00000000e+00, 2.20200539e+01],
         [9.96093750e-02, 2.20172462e+01],
         [1.99218750e-01, 2.20440521e+01],
         ...,
         [3.86524219e+03, 3.57263565e+01],
         [3.86534180e+03, 3.57337570e+01],
         [3.86546680e+03, 3.56881561e+01]]),
  array([[0.00000000e+00, 2.16604424e+01],
         [9.96093750e-02, 2.16222477e+01],
         [1.99218750e-01, 2.16298409e+01],
         ...,
         [3.86524219e+03, 3.68297577e+01],
         [3.86534180e+03, 3.68034554e+01],
         [3.86546680e+03, 3.67875443e+01]]),
  array([[0.00000000e+00, 2.18620491e+01],
         [9.96093750e-02, 2.18419266e+01],
         [1.99218750e-01, 2.18120174e+01],
         ...,
         [3.86524219e+03, 5.27296486e+01],
         [3.86534180e+03, 5.27283707e+01],
         [3.86546680e+03, 5.26857948e+01]]),
  array([[0.00000000e+00, 2.19145622e+01],
         [9.96093750e-02, 2.19015522e+01],
         [1.99218750e-01, 2.19063606e+01],
         ...,
         [3.86524219e+03, 5.50189476e+01],
         [3.86534180e+03, 5.50227280e+01],
         [3.86546680e+03, 5.50282173e+01]]),
  array([[ 0.     , 22.97453],
         [ 0.266  , 22.93832],
         [ 0.499  , 22.93832],
         ...,
         [     nan,      nan],
         [     nan,      nan],
         [     nan,      nan]]),
  array([[0.00000000e+00, 1.75270634e+01],
         [9.96093750e-02, 1.75128231e+01],
         [1.99218750e-01, 1.75219555e+01],
         ...,
         [3.84452344e+03, 2.04569588e+01],
         [3.84462305e+03, 2.04710140e+01],
         [3.84471777e+03, 2.04272404e+01]]),
  array([[0.00000000e+00, 1.76327915e+01],
         [9.96093750e-02, 1.76569653e+01],
         [1.99218750e-01, 1.76160641e+01],
         ...,
         [3.84452344e+03, 2.39019718e+01],
         [3.84462305e+03, 2.39046803e+01],
         [3.84471777e+03, 2.38852139e+01]]),
  array([[0.00000000e+00, 1.73843651e+01],
         [9.96093750e-02, 1.73945541e+01],
         [1.99218750e-01, 1.73881073e+01],
         ...,
         [3.84452344e+03, 1.85409164e+01],
         [3.84462305e+03, 1.85621548e+01],
         [3.84471777e+03, 1.85566521e+01]]),
  array([[0.00000000e+00, 1.70990200e+01],
         [9.96093750e-02, 1.70546494e+01],
         [1.99218750e-01, 1.70743217e+01],
         ...,
         [3.84452344e+03, 2.06275444e+01],
         [3.84462305e+03, 2.05973129e+01],
         [3.84471777e+03, 2.06331234e+01]]),
  array([[0.00000000e+00, 1.72298412e+01],
         [9.96093750e-02, 1.72237701e+01],
         [1.99218750e-01, 1.72233467e+01],
         ...,
         [3.84452344e+03, 2.21493797e+01],
         [3.84462305e+03, 2.21422215e+01],
         [3.84471777e+03, 2.21504993e+01]]),
  array([[0.00000000e+00, 1.73931255e+01],
         [9.96093750e-02, 1.74205246e+01],
         [1.99218750e-01, 1.74304047e+01],
         ...,
         [3.84452344e+03, 2.18155212e+01],
         [3.84462305e+03, 2.18160286e+01],
         [3.84471777e+03, 2.17781124e+01]]),
  array([[ 0.      , 22.308289],
         [ 0.048   , 21.98334 ],
         [ 0.097   , 21.948115],
         ...,
         [      nan,       nan],
         [      nan,       nan],
         [      nan,       nan]]),
  array([[1.00030000e+01, 2.46880000e+01],
         [2.00320000e+01, 2.48410000e+01],
         [3.00480000e+01, 2.46270000e+01],
         ...,
         [3.03065673e+07, 2.52320000e+01],
         [3.03065683e+07, 2.52320000e+01],
         [3.03065685e+07, 2.52320000e+01]]),
  array([[ 0.   , 24.206],
         [ 0.2  , 24.191],
         [ 0.4  , 24.199],
         ...,
         [   nan,    nan],
         [   nan,    nan],
         [   nan,    nan]]),
  array([[0.00000000e+00, 2.24510860e+01],
         [9.96093750e-02, 2.24354153e+01],
         [1.99218750e-01, 2.24313164e+01],
         ...,
         [3.86105859e+03, 4.22675133e+01],
         [3.86115820e+03, 4.22536621e+01],
         [3.86124512e+03, 4.22265472e+01]]),
  array([[0.00000000e+00, 2.24885426e+01],
         [9.96093750e-02, 2.25059147e+01],
         [1.99218750e-01, 2.24725895e+01],
         ...,
         [3.86105859e+03, 4.05943336e+01],
         [3.86115820e+03, 4.05768547e+01],
         [3.86124512e+03, 4.05714684e+01]]),
  array([[0.00000000e+00, 2.22406120e+01],
         [9.96093750e-02, 2.22403889e+01],
         [1.99218750e-01, 2.22518616e+01],
         ...,
         [3.86105859e+03, 4.02332344e+01],
         [3.86115820e+03, 4.02353134e+01],
         [3.86124512e+03, 4.02175941e+01]]),
  array([[0.00000000e+00, 2.19232807e+01],
         [9.96093750e-02, 2.19479084e+01],
         [1.99218750e-01, 2.19345531e+01],
         ...,
         [3.86105859e+03, 4.14929848e+01],
         [3.86115820e+03, 4.14898796e+01],
         [3.86124512e+03, 4.14575768e+01]]),
  array([[0.00000000e+00, 2.20563602e+01],
         [9.96093750e-02, 2.20646667e+01],
         [1.99218750e-01, 2.20431633e+01],
         ...,
         [3.86105859e+03, 5.44080353e+01],
         [3.86115820e+03, 5.44201431e+01],
         [3.86124512e+03, 5.44315376e+01]]),
  array([[0.00000000e+00, 2.22085991e+01],
         [9.96093750e-02, 2.22277508e+01],
         [1.99218750e-01, 2.22008724e+01],
         ...,
         [3.86105859e+03, 5.64516907e+01],
         [3.86115820e+03, 5.64308128e+01],
         [3.86124512e+03, 5.64215508e+01]]),
  array([[ 0.      , 21.777966],
         [ 0.049   , 21.74032 ],
         [ 0.094   , 21.782738],

In [1]:
from src.data import DataBundle, Dataset
from src.utils.config import import_config
from src.data.train_test_split import *
import numpy as np
import torch

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
x1, x2, y1, y2 = load_train_test_split(configs=config, dtype='numpy')
bundle = DataBundle(x1, y1, x2, y2)
# ds1 = Dataset(x1, y1)
# ds2 = Dataset(x2, y2)
# # len(ds1), len(ds2)
# ds1.feature

# npx1 = np.array(x1, dtype=object)

# torchx1 = torch.nested.nested_tensor([torch.from_numpy(arr).float() for arr in x1])
# torchy1 = torch.tensor(y1).float()
# torchy1
bundle

/Users/Hanita/Library/Python/3.12/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Missing expected config fields: ['t']

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3605.45it/s]

In [3]:
from src.data import DataBundle, Dataset
from src.utils.config import import_config
from src.data.train_test_split import *

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
x1, x2, y1, y2 = load_train_test_split(configs=config, dtype='tensor')
bundle = DataBundle(torch.nested.nested_tensor(x1), y1, torch.nested.nested_tensor(x2), y2)

# from src.models import NNModel, MLPRULPredictor, LSTMRULPredictor, DummyRULPredictor

# nn_model = DummyRULPredictor()

# nn_model.fit(bundle)

Missing expected config fields: ['t']

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3657.45it/s]

RuntimeError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue.

In [16]:
from src.data import BatteryData
from src.data.train_test_split import *


from src.utils.config import import_config
from src.data.experiment_dataset import *

configs = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
dirname = 'data/preprocessed/'
filename = 'data/preprocessed/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
battery_data = BatteryData.load(filename)

datalist = extract_attributes_from_dir(dirname, configs=configs['train_test_split'])
datalist, len(datalist)

Missing expected config fields: ['t']

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 2968.47it/s]

([(tensor([[6.0000e-02, 2.4772e+01],
           [7.2040e+00, 2.4772e+01],
           [7.2040e+00, 2.4772e+01],
           ...,
           [1.2360e+07, 3.0202e+01],
           [1.2360e+07, 3.0409e+01],
           [1.2360e+07, 3.0348e+01]]),
   tensor(1.)),
  (tensor([[1.0011e+01, 2.6155e+01],
           [2.0014e+01, 2.6155e+01],
           [3.0023e+01, 2.6231e+01],
           ...,
           [9.4971e+06, 2.8979e+01],
           [9.4971e+06, 2.9040e+01],
           [9.4971e+06, 2.9040e+01]]),
   tensor(1.)),
  (tensor([[1.0600e+00, 2.1300e+01],
           [2.0600e+00, 2.1300e+01],
           [3.0600e+00, 2.1300e+01],
           ...,
           [4.0271e+03, 1.9800e+01],
           [4.0281e+03, 1.9800e+01],
           [4.0291e+03, 1.9800e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.1300e+01],
           [2.0600e+00, 2.1300e+01],
           [3.0600e+00, 2.1300e+01],
           ...,
           [4.0271e+03, 2.1500e+01],
           [4.0281e+03, 2.1500e+01],
           [4.0291e+03, 2.1400e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.1400e+01],
           [2.0600e+00, 2.1400e+01],
           [3.0600e+00, 2.1500e+01],
           ...,
           [4.0271e+03, 2.0300e+01],
           [4.0281e+03, 2.0400e+01],
           [4.0291e+03, 2.0400e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.1500e+01],
           [2.0600e+00, 2.1500e+01],
           [3.0600e+00, 2.1500e+01],
           ...,
           [4.0271e+03, 2.1600e+01],
           [4.0281e+03, 2.1600e+01],
           [4.0291e+03, 2.1600e+01]]),
   tensor(0.)),
  (tensor([[6.2000e-02, 2.7623e+01],
           [2.5317e+01, 2.7441e+01],
           [1.0275e+02, 2.7410e+01],
           ...,
           [1.0018e+07, 2.9137e+01],
           [1.0019e+07, 2.9107e+01],
           [1.0019e+07, 2.9150e+01]]),
   tensor(1.)),
  (tensor([[ 0.0000, 23.1267],
           [ 0.0450, 23.0843],
           [ 0.0900, 23.1267],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 21.9281],
           [ 0.0990, 21.9433],
           [ 0.2330, 21.9228],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 22.2259],
           [ 0.0850, 22.1130],
           [ 0.1460, 22.1154],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 20.2657],
           [ 0.2000, 20.3144],
           [ 0.3000, 20.2946],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.3000e+01],
           [2.0600e+00, 2.2900e+01],
           [3.0600e+00, 2.3000e+01],
           ...,
           [3.7971e+03, 2.5000e+01],
           [3.7981e+03, 2.5000e+01],
           [3.7991e+03, 2.4900e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.2900e+01],
           [2.0600e+00, 2.2900e+01],
           [3.0600e+00, 2.2900e+01],
           ...,
           [3.7971e+03, 2.9400e+01],
           [3.7981e+03, 2.9400e+01],
           [3.7991e+03, 2.9400e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.2900e+01],
           [2.0600e+00, 2.2900e+01],
           [3.0600e+00, 2.2900e+01],
           ...,
           [3.7971e+03, 2.7100e+01],
           [3.7981e+03, 2.7100e+01],
           [3.7991e+03, 2.7100e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.3000e+01],
           [2.0600e+00, 2.2900e+01],
           [3.0600e+00, 2.3000e+01],
           ...,
           [3.7971e+03, 2.4800e+01],
           [3.7981e+03, 2.4800e+01],
           [3.7991e+03, 2.4800e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.1802e+01],
           [9.9609e-02, 2.1844e+01],
           [1.9922e-01, 2.1818e+01],
           ...,
           [3.8578e+03, 3.1489e+01],
           [3.8579e+03, 3.1477e+01],
           [3.8581e+03, 3.1504e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.1890e+01],
           [9.9609e-02, 2.1914e+01],
           [1.9922e-01, 2.1909e+01],
           ...,
           [3.8578e+03, 3.0894e+01],
           [3.8579e+03, 3.0914e+01],
           [3.8581e+03, 3.0922e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.1613e+01],
           [9.9609e-02, 2.1582e+01],
           [1.9922e-01, 2.1597e+01],
           ...,
           [3.8578e+03, 2.9855e+01],
           [3.8579e+03, 2.9900e+01],
           [3.8581e+03, 2.9845e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.1327e+01],
           [9.9609e-02, 2.1286e+01],
           [1.9922e-01, 2.1323e+01],
           ...,
           [3.8578e+03, 3.0430e+01],
           [3.8579e+03, 3.0413e+01],
           [3.8581e+03, 3.0450e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 22.9109],
           [ 0.0990, 22.8969],
           [ 0.2000, 22.8993],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 22.3019],
           [ 0.0920, 22.2243],
           [ 0.1370, 22.4644],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 23.7800],
           [ 0.2000, 23.7880],
           [ 0.4000, 23.7910],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.7173e+01],
           [9.9609e-02, 1.7179e+01],
           [1.9922e-01, 1.7208e+01],
           ...,
           [3.8125e+03, 1.9595e+01],
           [3.8126e+03, 1.9593e+01],
           [3.8128e+03, 1.9636e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.7342e+01],
           [9.9609e-02, 1.7328e+01],
           [1.9922e-01, 1.7322e+01],
           ...,
           [3.8125e+03, 1.8788e+01],
           [3.8126e+03, 1.8759e+01],
           [3.8128e+03, 1.8779e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.7100e+01],
           [9.9609e-02, 1.7107e+01],
           [1.9922e-01, 1.7109e+01],
           ...,
           [3.8125e+03, 2.2729e+01],
           [3.8126e+03, 2.2713e+01],
           [3.8128e+03, 2.2708e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.6781e+01],
           [9.9609e-02, 1.6776e+01],
           [1.9922e-01, 1.6766e+01],
           ...,
           [3.8125e+03, 1.9044e+01],
           [3.8126e+03, 1.9070e+01],
           [3.8128e+03, 1.9060e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 24.0550],
           [ 0.2000, 24.0690],
           [ 0.4000, 24.0570],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 24.3220],
           [ 0.2000, 24.3210],
           [ 0.4000, 24.3180],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2364e+01],
           [9.9609e-02, 2.2359e+01],
           [1.9922e-01, 2.2365e+01],
           ...,
           [3.8563e+03, 2.9108e+01],
           [3.8564e+03, 2.9104e+01],
           [3.8565e+03, 2.9110e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2441e+01],
           [9.9609e-02, 2.2418e+01],
           [1.9922e-01, 2.2377e+01],
           ...,
           [3.8563e+03, 2.8774e+01],
           [3.8564e+03, 2.8783e+01],
           [3.8565e+03, 2.8805e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2112e+01],
           [9.9609e-02, 2.2142e+01],
           [1.9922e-01, 2.2148e+01],
           ...,
           [3.8563e+03, 2.8461e+01],
           [3.8564e+03, 2.8413e+01],
           [3.8565e+03, 2.8468e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.1875e+01],
           [9.9609e-02, 2.1842e+01],
           [1.9922e-01, 2.1871e+01],
           ...,
           [3.8563e+03, 2.8376e+01],
           [3.8564e+03, 2.8373e+01],
           [3.8565e+03, 2.8379e+01]]),
   tensor(0.)),
  (tensor([[1.0000e+01, 3.4901e+01],
           [2.0002e+01, 3.4906e+01],
           [3.0007e+01, 3.4897e+01],
           ...,
           [5.0867e+06, 3.4673e+01],
           [5.0867e+06, 3.4673e+01],
           [5.0867e+06, 3.4673e+01]]),
   tensor(1.)),
  (tensor([[ 0.0000, 23.0861],
           [ 0.0460, 22.9238],
           [ 0.0920, 23.0061],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 23.7720],
           [ 0.2000, 23.7690],
           [ 0.4000, 23.7600],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.8400e+01],
           [2.0600e+00, 1.8400e+01],
           [3.0600e+00, 1.8400e+01],
           ...,
           [4.0691e+03, 2.0700e+01],
           [4.0701e+03, 2.0700e+01],
           [4.0711e+03, 2.0700e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.8400e+01],
           [2.0600e+00, 1.8400e+01],
           [3.0600e+00, 1.8400e+01],
           ...,
           [4.0691e+03, 2.0900e+01],
           [4.0701e+03, 2.0800e+01],
           [4.0711e+03, 2.0800e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.8500e+01],
           [2.0600e+00, 1.8500e+01],
           [3.0600e+00, 1.8500e+01],
           ...,
           [4.0691e+03, 2.1100e+01],
           [4.0701e+03, 2.1100e+01],
           [4.0711e+03, 2.1100e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.8500e+01],
           [2.0600e+00, 1.8500e+01],
           [3.0600e+00, 1.8500e+01],
           ...,
           [4.0691e+03, 2.0700e+01],
           [4.0701e+03, 2.0700e+01],
           [4.0711e+03, 2.0800e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.6300e+01],
           [2.0600e+00, 2.6300e+01],
           [3.0600e+00, 2.6300e+01],
           ...,
           [2.8471e+03, 3.1000e+01],
           [2.8481e+03, 3.1000e+01],
           [2.8491e+03, 3.1000e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.6200e+01],
           [2.0600e+00, 2.6200e+01],
           [3.0600e+00, 2.6200e+01],
           ...,
           [2.8471e+03, 3.5600e+01],
           [2.8481e+03, 3.5600e+01],
           [2.8491e+03, 3.5600e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.6200e+01],
           [2.0600e+00, 2.6200e+01],
           [3.0600e+00, 2.6200e+01],
           ...,
           [2.8471e+03, 2.8700e+01],
           [2.8481e+03, 2.8800e+01],
           [2.8491e+03, 2.8800e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.6300e+01],
           [2.0600e+00, 2.6300e+01],
           [3.0600e+00, 2.6300e+01],
           ...,
           [2.8471e+03, 3.2300e+01],
           [2.8481e+03, 3.2300e+01],
           [2.8491e+03, 3.2200e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 21.8145],
           [ 0.0850, 21.6961],
           [ 0.1310, 21.7361],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 22.2582],
           [ 0.0990, 22.2419],
           [ 0.1990, 22.2366],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2164e+01],
           [9.9609e-02, 2.2147e+01],
           [1.9922e-01, 2.2136e+01],
           ...,
           [3.8652e+03, 3.7695e+01],
           [3.8653e+03, 3.7688e+01],
           [3.8655e+03, 3.7674e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2204e+01],
           [9.9609e-02, 2.2212e+01],
           [1.9922e-01, 2.2204e+01],
           ...,
           [3.8652e+03, 3.6803e+01],
           [3.8653e+03, 3.6761e+01],
           [3.8655e+03, 3.6728e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2020e+01],
           [9.9609e-02, 2.2017e+01],
           [1.9922e-01, 2.2044e+01],
           ...,
           [3.8652e+03, 3.5726e+01],
           [3.8653e+03, 3.5734e+01],
           [3.8655e+03, 3.5688e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.1660e+01],
           [9.9609e-02, 2.1622e+01],
           [1.9922e-01, 2.1630e+01],
           ...,
           [3.8652e+03, 3.6830e+01],
           [3.8653e+03, 3.6803e+01],
           [3.8655e+03, 3.6788e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 22.9745],
           [ 0.2660, 22.9383],
           [ 0.4990, 22.9383],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.7527e+01],
           [9.9609e-02, 1.7513e+01],
           [1.9922e-01, 1.7522e+01],
           ...,
           [3.8445e+03, 2.0457e+01],
           [3.8446e+03, 2.0471e+01],
           [3.8447e+03, 2.0427e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.7633e+01],
           [9.9609e-02, 1.7657e+01],
           [1.9922e-01, 1.7616e+01],
           ...,
           [3.8445e+03, 2.3902e+01],
           [3.8446e+03, 2.3905e+01],
           [3.8447e+03, 2.3885e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.7384e+01],
           [9.9609e-02, 1.7395e+01],
           [1.9922e-01, 1.7388e+01],
           ...,
           [3.8445e+03, 1.8541e+01],
           [3.8446e+03, 1.8562e+01],
           [3.8447e+03, 1.8557e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.7099e+01],
           [9.9609e-02, 1.7055e+01],
           [1.9922e-01, 1.7074e+01],
           ...,
           [3.8445e+03, 2.0628e+01],
           [3.8446e+03, 2.0597e+01],
           [3.8447e+03, 2.0633e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 22.3083],
           [ 0.0480, 21.9833],
           [ 0.0970, 21.9481],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[1.0003e+01, 2.4688e+01],
           [2.0032e+01, 2.4841e+01],
           [3.0048e+01, 2.4627e+01],
           ...,
           [3.0307e+07, 2.5232e+01],
           [3.0307e+07, 2.5232e+01],
           [3.0307e+07, 2.5232e+01]]),
   tensor(1.)),
  (tensor([[ 0.0000, 24.2060],
           [ 0.2000, 24.1910],
           [ 0.4000, 24.1990],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2451e+01],
           [9.9609e-02, 2.2435e+01],
           [1.9922e-01, 2.2431e+01],
           ...,
           [3.8611e+03, 4.2268e+01],
           [3.8612e+03, 4.2254e+01],
           [3.8612e+03, 4.2227e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2489e+01],
           [9.9609e-02, 2.2506e+01],
           [1.9922e-01, 2.2473e+01],
           ...,
           [3.8611e+03, 4.0594e+01],
           [3.8612e+03, 4.0577e+01],
           [3.8612e+03, 4.0571e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2241e+01],
           [9.9609e-02, 2.2240e+01],
           [1.9922e-01, 2.2252e+01],
           ...,
           [3.8611e+03, 4.0233e+01],
           [3.8612e+03, 4.0235e+01],
           [3.8612e+03, 4.0218e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.1923e+01],
           [9.9609e-02, 2.1948e+01],
           [1.9922e-01, 2.1935e+01],
           ...,
           [3.8611e+03, 4.1493e+01],
           [3.8612e+03, 4.1490e+01],
           [3.8612e+03, 4.1458e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 21.7780],
           [ 0.0490, 21.7403],
           [ 0.0940, 21.7827],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[1.0002e+01, 3.4838e+01],
           [2.0000e+01, 3.4847e+01],
           [3.0003e+01, 3.4821e+01],
           ...,
           [6.3458e+06, 3.4638e+01],
           [6.3458e+06, 3.4638e+01],
           [6.3458e+06, 3.4638e+01]]),
   tensor(1.)),
  (tensor([[1.0600e+00, 2.2500e+01],
           [2.0600e+00, 2.2500e+01],
           [3.0600e+00, 2.2500e+01],
           ...,
           [4.0051e+03, 3.0300e+01],
           [4.0061e+03, 3.0300e+01],
           [4.0071e+03, 3.0300e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.2500e+01],
           [2.0600e+00, 2.2500e+01],
           [3.0600e+00, 2.2500e+01],
           ...,
           [4.0051e+03, 3.3500e+01],
           [4.0061e+03, 3.3500e+01],
           [4.0071e+03, 3.3500e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.2500e+01],
           [2.0600e+00, 2.2500e+01],
           [3.0600e+00, 2.2400e+01],
           ...,
           [4.0051e+03, 3.3600e+01],
           [4.0061e+03, 3.3600e+01],
           [4.0071e+03, 3.3600e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.2600e+01],
           [2.0600e+00, 2.2600e+01],
           [3.0600e+00, 2.2600e+01],
           ...,
           [4.0051e+03, 3.4300e+01],
           [4.0061e+03, 3.4300e+01],
           [4.0071e+03, 3.4200e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 21.6751],
           [ 0.0760, 21.6775],
           [ 0.1210, 21.6823],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 21.7498],
           [ 0.0460, 21.7850],
           [ 0.0990, 21.7073],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.6634e+01],
           [9.9609e-02, 1.6664e+01],
           [1.9922e-01, 1.6647e+01],
           ...,
           [3.8022e+03, 1.7561e+01],
           [3.8023e+03, 1.7552e+01],
           [3.8025e+03, 1.7556e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.6762e+01],
           [9.9609e-02, 1.6770e+01],
           [1.9922e-01, 1.6750e+01],
           ...,
           [3.8022e+03, 2.0166e+01],
           [3.8023e+03, 2.0185e+01],
           [3.8025e+03, 2.0219e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.6536e+01],
           [9.9609e-02, 1.6517e+01],
           [1.9922e-01, 1.6517e+01],
           ...,
           [3.8022e+03, 2.4440e+01],
           [3.8023e+03, 2.4407e+01],
           [3.8025e+03, 2.4440e+01]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 1.6157e+01],
           [9.9609e-02, 1.6178e+01],
           [1.9922e-01, 1.6219e+01],
           ...,
           [3.8022e+03, 1.8938e+01],
           [3.8023e+03, 1.8929e+01],
           [3.8025e+03, 1.8940e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 24.1890],
           [ 0.2000, 24.1990],
           [ 0.4000, 24.1920],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 23.8160],
           [ 0.2000, 23.8250],
           [ 0.4000, 23.8250],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[0.0000e+00, 2.2397e+01],
           [6.7000e-02, 2.2398e+01],
           [2.0000e-01, 2.2395e+01],
           ...,
           [6.1678e+02, 5.4346e+01],
           [6.1685e+02, 5.4313e+01],
           [6.1695e+02, 5.4312e+01]]),
   tensor(0.)),
  (tensor([[ 0.0000, 24.4780],
           [ 0.2000, 24.4860],
           [ 0.4000, 24.4860],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[ 0.0000, 24.3390],
           [ 0.2000, 24.3420],
           [ 0.4000, 24.3360],
           ...,
           [    nan,     nan],
           [    nan,     nan],
           [    nan,     nan]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.6000e+01],
           [2.0600e+00, 1.6000e+01],
           [3.0600e+00, 1.6000e+01],
           ...,
           [3.9721e+03, 3.1000e+01],
           [3.9731e+03, 3.0800e+01],
           [3.9741e+03, 3.0800e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.6000e+01],
           [2.0600e+00, 1.6000e+01],
           [3.0600e+00, 1.6000e+01],
           ...,
           [3.9721e+03, 3.0400e+01],
           [3.9731e+03, 3.0400e+01],
           [3.9741e+03, 3.0400e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.6000e+01],
           [2.0600e+00, 1.6000e+01],
           [3.0600e+00, 1.6000e+01],
           ...,
           [3.9721e+03, 3.3200e+01],
           [3.9731e+03, 3.3000e+01],
           [3.9741e+03, 3.2900e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 1.6200e+01],
           [2.0600e+00, 1.6200e+01],

In [47]:
from src.data.experiment_dataset import * 
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

class ExperimentDataset(torch.utils.data.Dataset):
    def __init__(self, data = []):
        self.data = data 

    def __getitem__(self, idx):
        return self.data[idx]
    
    def __len__(self):
        return len(self.data)
    
    def append_data(self, data):
        self.data += data 
    
    def add(self, feature, label):
        self.data.append((feature, label))

def collate_fn(batch):
    sequences, labels = zip(*batch)
    padded = pad_sequence(sequences, batch_first=True)  # shape: (B, T_max, D)
    lengths = torch.tensor([seq.size(0) for seq in sequences])
    labels = torch.stack(labels)  # shape: (B,)
    return padded, labels, lengths

train_data, test_data = load_train_test_split()

train_dataset = ExperimentDataset(train_data)
test_dataset = ExperimentDataset(test_data)

train_loader = DataLoader(train_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)
# for padded_batch, label_batch, lengths in test_loader:
#     print(f"Padded: {padded_batch.shape}, Labels: {label_batch}, Lengths: {lengths}")
#     break  # one batch only

batch = next(iter(test_loader))
print(batch[0].size(), batch[1].size(), batch[2].size())
batch[0].size(-1)
# print(f"Feature batch shape: {test_features.size()}")
# print(f"Labels batch shape: {test_labels.size()}")

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 1329.15it/s]

torch.Size([40, 596958, 2]) torch.Size([40]) torch.Size([40])

2

In [48]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, layer_dim, output_dim):
        super(LSTMModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.layer_dim = layer_dim
        self.lstm = nn.LSTM(input_dim, hidden_dim, layer_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, h0=None, c0=None):
        if h0 is None or c0 is None:
            h0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
            c0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
        
        out, (hn, cn) = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out, hn, cn
    

model = LSTMModel(input_dim=2, hidden_dim=100, layer_dim=1, output_dim=1)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

def trainLSTM(model, dataloader, criterion, num_epochs=3):
    device = 'cpu'

    model.to(device)
    model.train()

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    h0, c0 = None, None

    for epoch in range(num_epochs):
        epoch_loss = 0.0
        for batch in dataloader:
            outputs, h0, c0 = model(batch[0], h0, c0)

            loss = criterion(outputs, batch[1])
            loss.backward()
            optimizer.step()

            h0 = h0.detach()
            c0 = c0.detach()

        avg_loss = epoch_loss / len(dataloader)
        print(f"Epoch {epoch}/{num_epochs}, Loss: {avg_loss:.4f}")

    
trainLSTM(model, train_loader, criterion)

/Users/Hanita/Library/Python/3.12/lib/python/site-packages/torch/nn/modules/loss.py:538: UserWarning: Using a target size (torch.Size([40])) that is different to the input size (torch.Size([40, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

In [5]:
from src.models import NNModel, MLPRULPredictor, MultiLayerPerceptronModule, LSTMRULPredictor
from src.data import DataBundle

# Licensed under the MIT License.
# Copyright (c) Microsoft Corporation.
from sklearn.metrics import roc_auc_score
import abc
import torch
import random
import numpy as np
import torch.nn as nn
import torch.optim as optim

from tqdm import tqdm
from torch.utils.data.dataloader import DataLoader

from src.data import DataBundle

from .base import BaseModel


def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)


class NNModel(BaseModel, nn.Module, abc.ABC):
    def __init__(self,
                 batch_size: int = 32,
                 epochs: int = 10000,
                 workspace: str = None,
                 evaluate_freq: int = 500,
                 checkpoint_freq: int = 1000,
                 train_batch_size: int = None,
                 test_batch_size: int = None,
                 lr: float = 1e-3):
        nn.Module.__init__(self)
        BaseModel.__init__(self, workspace)
        self.train_epochs = epochs
        self.evaluate_freq = evaluate_freq
        if checkpoint_freq is None or checkpoint_freq == 'None':
            self.checkpoint_freq = None
        else:
            self.checkpoint_freq = min(checkpoint_freq, self.train_epochs)
        self.train_batch_size = train_batch_size or batch_size
        self.test_batch_size = test_batch_size or batch_size
        self.lr = lr

    def fit(self,
            trainloader,
            testloader,
            traindataset,
            testdataset,
            timestamp: str = None,
            seed: int = 0):
        self.train()
        # train_data = dataset.train_data
        # loader = DataLoader(
        #     train_data, self.train_batch_size,
        #     shuffle=True, worker_init_fn=seed_worker)
        loader = train_loader
        # TODO: support customization of optimizers
        optimizer = optim.Adam(self.parameters(), lr=self.lr)

        timestamp = timestamp or 'UnknownTime'

        latest = None
        for epoch in tqdm(range(self.train_epochs), desc='Traning'):
            self.train()
            for batch in loader:
                loss = self.forward(**batch, return_loss=True)
                if loss == torch.inf:
                    reset_parameters(self)
                    optimizer = optim.Adam(self.parameters(), lr=self.lr)
                else:
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

            if self.checkpoint_freq is not None and \
                    (epoch + 1) % self.checkpoint_freq == 0:
                filename = f'{timestamp}_seed_{seed}_epoch_{epoch+1}.ckpt'
                if self.workspace is not None:
                    self.dump_checkpoint(self.workspace / filename)
                    latest = self.workspace / filename

            if (epoch + 1) % self.evaluate_freq == 0:
                pred = self.predict(testdataset)
                score = roc_auc_score(testdataset, prediction)
                print(f'[{epoch+1}/{self.train_epochs}] RMSE {score:.2f}', flush=True)

        if self.workspace is not None:
            self.link_latest_checkpoint(latest)

    @torch.no_grad()
    def predict(self, dataset, data_type: str='test') -> torch.Tensor:
        self.eval()
        # test_data = dataset.test_data
        if data_type == 'test':
            test_data = dataset.test_data
        else:
            test_data = dataset.train_data
            
        loader = DataLoader(
            test_data, self.test_batch_size,
            shuffle=False, worker_init_fn=seed_worker)
        predictions = torch.cat([self.forward(**batch) for batch in loader])
        return predictions

    def to(self, device: str):
        return nn.Module.to(self, device)

    def dump_checkpoint(self, path: str):
        torch.save(self.state_dict(), path)

    def load_checkpoint(self, path: str):
        self.load_state_dict(torch.load(path))


def reset_parameters(model):
    @torch.no_grad()
    def weight_reset(m):
        reset_parameters = getattr(m, "reset_parameters", None)
        if callable(reset_parameters):
            m.reset_parameters()

    model.apply(weight_reset)


train_loader = DataLoader(train_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)

bundle = DataBundle(train_data=train_dataset, test_data=test_dataset)
nn_model = NNModel(
    batch_size=10,
    epochs=2
)

# nn_model.fit(bundle)
mlp = MLPRULPredictor(
    in_channels=2,
    channels=1,
    input_height=2,
    input_width=2,
    batch_size=10,
    epochs=2
)
mlp.fit(bundle)

Traning:   0%|          | 0/2 [00:00<?, ?it/s]

RuntimeError: stack expects each tensor to be equal size, but got [22410, 2] at entry 0 and [102167, 2] at entry 1

In [3]:
import os 
import torch
import numpy as np
from glob import glob 
from tqdm.auto import tqdm
from sklearn.model_selection import train_test_split

from src.config import config
from src.data import BatteryData, DataBundle

from src.data.train_test_split import * 
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    sequences, labels = zip(*batch)
    padded = pad_sequence(sequences, batch_first=True)  # shape: (B, T_max, D)
    lengths = torch.tensor([seq.size(0) for seq in sequences])
    labels = torch.stack(labels)  # shape: (B,)
    return padded, labels, lengths

# from src.utils.config import import_config

# configs = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
dirname = 'data/preprocessed/'

X_train, X_test, y_train, y_test = load_train_test_split(dirname, dtype=torch.tensor)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

bundle = DataBundle(X_train, y_train, X_test, y_test)
len(bundle.train_data)
len(bundle.test_data)

from src.models import DummyRULPredictor, LSTMRULPredictor, MLPRULPredictor

dummy = DummyRULPredictor()
dummy.fit(bundle)
dummy.predict(bundle)

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 853.11it/s]

torch.Size([489, 2020541, 2]) torch.Size([123, 2020541, 2]) torch.Size([489]) torch.Size([123])

tensor([0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861])

In [9]:
from src.models.dummy import SklearnModel
from sklearn.linear_model import LinearRegression

class LinearRegressionRULPredictor(SklearnModel):
    def __init__(self, *args, workspace: str = None, **kwargs):
        SklearnModel.__init__(self, workspace)
        self.model = LinearRegression(*args, **kwargs)

linreg = LinearRegressionRULPredictor()
linreg.fit(bundle)
predictions = linreg.predict(bundle)
torch.round(predictions)

tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
mlp = MLPRULPredictor(
    in_channels=1,
    channels=1,
    input_height=596958,
    input_width=2, 
    epochs=2
)

mlp.fit(bundle)
mlp.predict(bundle)

Traning: 100%|██████████| 2/2 [00:05<00:00,  2.68s/it]

tensor([0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779])

In [11]:
import random 
from pathlib import Path
from datetime import datetime

def set_seed(seed: int):
    print(f'Seed is set to {seed}.')
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

def timestamp(marker: bool = False):
    template = '%Y-%m-%d %H:%M:%S' if marker else '%Y%m%d%H%M%S'
    return datetime.now().strftime(template)


def train(model, databundle, criterion=None, num_epochs=3):
    set_seed(0)
    device = 'cpu'

    model = model.to(device)
    ts = timestamp()

    model.fit(databundle, timestamp=ts)
    return model, databundle

model = MLPRULPredictor(
    in_channels=1,
    channels=32,
    input_height=596958,
    input_width=2, 
    epochs=10,
    batch_size=128,
)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

model, _ = train(model, bundle)
model.predict(bundle)

Seed is set to 0.

Training:   0%|          | 0/10 [00:00<?, ?it/s]

In [1]:
import torch
import torch.nn as nn
from src.utils.config import import_config
from src.data import DataBundle
from src.data.train_test_split import *
from src.models import *
configs = import_config('configs/mini.yaml', ['train_test_split'])
dirname = 'data/preprocessed/'

X_train, X_test, y_train, y_test = load_train_test_split(dirname, configs=configs, dtype=torch.tensor, test_size=0.5)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

mini_bundle = DataBundle(X_train, y_train, X_test, y_test)

class LSTMRULPredictor(NNModel):
    def __init__(self,
                input_size: int,
                hidden_size: int,
                 **kwargs):
        """
        Args:
            in_channels (int): 
        """
        NNModel.__init__(self, **kwargs)

        self.lstm = nn.LSTM(
            input_size, hidden_size, 2, batch_first=True)
        in_features = hidden_size
        self.fc = nn.Linear(in_features, 1)

    def forward(self,
                feature: torch.Tensor,
                label: torch.Tensor,
                return_loss: bool = False):
        if feature.ndim == 3:
            feature = feature.unsqueeze(1)
        B, _, H, _ = feature.size()
        x = feature.permute(0, 2, 1, 3).contiguous().view(B, H, -1)
        x, _ = self.lstm(x)
        x = x[:, -1].contiguous().view(B, -1)
        x = self.fc(x).view(-1)
        x = torch.sigmoid(x)

        if return_loss:
            # return torch.mean((x - label.view(-1)) ** 2)
            return nn.functional.binary_cross_entropy(x, label.view(-1))

        return x
    
my_lstm = LSTMRULPredictor(
    input_size=2,
    hidden_size=1,
    epochs=3,
)

/Users/Hanita/Library/Python/3.12/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3008.76it/s]

torch.Size([56, 128943, 2]) torch.Size([56, 128943, 2]) torch.Size([56]) torch.Size([56])

In [2]:
my_lstm.fit(mini_bundle)

Training: 100%|██████████| 3/3 [01:52<00:00, 37.64s/it]

In [5]:
probs = my_lstm.predict(mini_bundle)
preds = (probs >= 0.5).int()
preds

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)

In [7]:
# configs = import_config('configs/mini.yaml', ['train_test_split'])
# dirname = 'data/preprocessed/'

# X_train, X_test, y_train, y_test = load_train_test_split(dirname, configs=configs, dtype=torch.tensor, test_size=0.5)
# print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

mini_bundle = DataBundle(X_train, y_train, X_test, y_test)
print(sum(mini_bundle.test_data.label))
mini_bundle.test_data.label

tensor(7.)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [6]:
probs = my_lstm.predict(mini_bundle)
preds = (probs >= 0.5).int()
preds

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)