In [1]:
from src.runner import preprocess
preprocess()

/Users/Hanita/Library/Python/3.12/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Processing Center for Advanced Life Cycle Engineering cells: 100%|██████████| 7/7 [00:01<00:00,  4.11it/s]

0 processed, 7 skipped

Processing Hawaii Natural Energy Institute cells: 100%|██████████| 15/15 [00:03<00:00,  3.80it/s]

0 processed, 15 skipped

Processing Oxford cells: 100%|██████████| 8/8 [00:01<00:00,  5.32it/s]

8 processed, 0 skipped

Processing Oak Ridge National Lab cells: 100%|██████████| 253/253 [01:20<00:00,  3.15it/s]

230 processed, 23 skipped

Processing Sandia National Lab cells: 100%|██████████| 30/30 [00:06<00:00,  4.42it/s]
Processing Sandia National Lab cells: 100%|██████████| 24/24 [00:02<00:00, 11.14it/s]
Processing Sandia National Lab cells: 100%|██████████| 32/32 [00:04<00:00,  7.25it/s]

74 processed, 12 skipped

Processing Underwriters Lab - Purdue University cells: 100%|██████████| 22/22 [00:03<00:00,  7.03it/s]

21 processed, 1 skipped

In [7]:
from src.data.battery_data import BatteryData
oxford_data = BatteryData.load('data/preprocessed/oxford/OX_1-1_pouch_LCO_40C_0-100_2-1.84C_a_timeseries.pkl')
oxford_data.print_description()
ts = next(t for t in oxford_data.timeseries_data)
ts.display()

**************description of battery cell OX_1-1_pouch_LCO_40C_0-100_2-1.84C_a_timeseries**************
cell_id: OX_1-1_pouch_LCO_40C_0-100_2-1.84C_a_timeseries
organization: oxford
timeseries_data: [<src.preprocessing.battery_data.TimeseriesData object at 0x33426fdd0>]
is_healthy: True
anode_material: graphite
cathode_material: LCO
nominal_capacity_in_Ah: 0.72
form_factor: pouch

            Time (s)  Temp (°C)
0       0.000000e+00     40.026
1       9.990000e-01     40.051
2       1.999000e+00     39.988
3       2.999000e+00     39.976
4       3.999000e+00     39.964
...              ...        ...
460376  5.518128e+07     40.737
460377  5.518128e+07     40.750
460378  5.518128e+07     40.688
460379  5.518128e+07     40.725
460380  5.518128e+07     40.750

[460381 rows x 2 columns]

In [8]:
from src.data.battery_data import BatteryData
filename = 'data/preprocessed/oakridge/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
data = BatteryData.load(filename)
data.print_description()
ts = next(t for t in data.timeseries_data)
ts.display()

**************description of battery cell SNL_LFP_Graphite_10Ah_100SOC_b**************
cell_id: SNL_LFP_Graphite_10Ah_100SOC_b
organization: snl
timeseries_data: [<src.preprocessing.battery_data.TimeseriesData object at 0x1766e6120>, <src.preprocessing.battery_data.TimeseriesData object at 0x33427c200>, <src.preprocessing.battery_data.TimeseriesData object at 0x33427ca10>, <src.preprocessing.battery_data.TimeseriesData object at 0x33427fef0>, <src.preprocessing.battery_data.TimeseriesData object at 0x33427d880>, <src.preprocessing.battery_data.TimeseriesData object at 0x33427fd10>]
is_healthy: False
state_of_charge: 100
battery_type: (None,)
anode_material: graphite
cathode_material: LFP
nominal_capacity_in_Ah: 10.0
form_factor: cylindrical_18650

          Time (s)  Temp (°C)
0         0.000000  22.364101
1         0.099609  22.358707
2         0.199219  22.365358
3         0.298828  22.381090
4         0.398438  22.315783
...            ...        ...
38712  3856.078125  29.106949
38713  3856.177734  29.090010
38714  3856.277344  29.108253
38715  3856.376953  29.104151
38716  3856.465820  29.110058

[38717 rows x 2 columns]

In [4]:
from src.data.train_test_split import *
from src.utils.config import YamlHandler
from sklearn.model_selection import train_test_split

configs=YamlHandler('configs/dummy.yaml').read_yaml()

configs = configs.train_test_split
features, labels = extract_attributes_from_dir(configs=configs)
print(len(features), type(features), len(labels), type(labels))

x1, x2, y1, y2 = load_train_test_split(configs=configs)
print(len(x1), len(x2), len(y1), len(y2))
# X_train, X_test, _, _ = load_train_test_split(configs=configs)

# print(len(X_test) + len(X_train))



# configs=YamlHandler('configs/default.yaml').read_yaml()
# X_train, X_test, _, _ = load_train_test_split(configs=configs)

# print(len(X_test) + len(X_train))

738 <class 'list'> 738 <class 'list'>
590 148 590 148

In [6]:
from src.utils.config import YamlHandler
from src.data.battery_data import BatteryData

handler = YamlHandler('configs/dummy.yaml')
config = handler.read_yaml()


config = config.get('train_test_split', config)
config

def testconfig(configs, data=None):
    configs = configs.get('train_test_split', configs) # open configs if needed

    for filter in configs.battery_filters:
        print(filter, type(filter))

        filterattr = getattr(configs.battery_filters, filter)
        dataattr = getattr(data, filter, None)
        print(filterattr)
        print(dataattr)

        print(dataattr in filterattr)
        print()

    print(any(getattr(data, filter, None) in getattr(configs.battery_filters, filter) for filter in configs.battery_filters))


filename = 'data/preprocessed/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
data = BatteryData.load(filename)

testconfig(config, data)
data.anode_material

anode_material <class 'str'>
['graphitee']
graphite
False

cathode_material <class 'str'>
['NMC']
LFP
False

False

'graphite'

In [3]:
from src.utils.config import import_config
from pathlib import Path

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
type(config)

Missing expected config fields: ['t']

dict